server:
  port: 8082
  servlet:
    context-path: /app
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wechat
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.app.model
mapper:
  identity: MYSQL
  mappers: tk.mybatis.mapper.common.BaseMapper
  not-empty: true
